### ISSUE TITLE
Does this work for read-only or can one also set values?

### ISSUE THREAD

**Issue by cibernox** [adamkrol93/wolf-smartset#2]
Hi,

I'm installing a wolf heat recuperator and I'm already planning on integrating it with home assistant. Since I can't still play with it I thought I could ask: Does this library (and the HA integration that uses it) allow to change parameters (in my case, air flow mostly) or it only polls state (read-only)?

Sorry for opening this as an issue when it's more like a question from future consumer too eager to wait till the home is finished to plan the setup.

**Comment by adamkrol93** [comment]
Hi,
Well, currently it is read only. I have plans to add parameters setting to this integration since I would also like to be able to run for example warm water heating on demand (from HA). But currently I am not sure when my plans are going to be realized.
Also I do not know how this system will work with heat recuperator, I do not have one, but I was trying to write this library as generic as possible.

**Comment by cibernox** [comment]
In that case I might be able to help in two months.
